<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<AssemblyName>ProjectOLDR</AssemblyName>
		<AssemblyTitle>Project OLDR</AssemblyTitle>
		<Company>OLDR Team</Company>
		<Product>Project OLDR</Product>
		<Description>Project OLDR Launcher</Description>
		<Copyright>Copyright (C) 2026 Nexoz</Copyright>
		<Version>1.0.0</Version>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<InformationalVersion>1.0.0</InformationalVersion>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>disable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>disable</ImplicitUsings>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="EmbeddedConfig.xml" />
	</ItemGroup>

	<ItemGroup>
		<None Include="libcrypto-4-x64.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="libssl-4-x64.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>